

services:

  mongo:
    container_name: mongo
    image: mongo
    env_file:
      - .env 
    environment:
      - MONGO_INITDB_ROOT_USERNAME=${MONGODB_ADMINUSERNAME}
      - MONGO_INITDB_ROOT_PASSWORD=${MONGODB_ADMINPASSWORD}
      - MONGO_INITDB_DATABASE=${DATABASE_NAME}
    volumes:
      - shared-data:/shared
    ports:
      - "${MONGODB_PORT}:27017"
    networks:
      - server-net
    deploy:
      resources:
        limits:
          cpus: '0.5'       # half CPU core
          memory: 512M      # 512 MB RAM
        reservations:
          cpus: '0.25'      # minimum CPU reserved
          memory: 256M      # minimum memory reserved


  # frontend:
  #   build:
  #     context: .
  #     dockerfile: ./docker/Dockerfile.frontend
  #   container_name: client
  #   env_file:
  #     - .env
  #   volumes:
  #     - shared-data:/shared
  #   ports:
  #     - "8080:4173"
  #   networks:
  #     - server-net
  #   depends_on:
  #     - mongo
  #   deploy:
  #     resources:
  #       limits:
  #         cpus: '0.5'
  #         memory: 512M 
  #       reservations:
  #         cpus: '0.50'
  #         memory: 256M 

  server:
    build:
      context: .
      dockerfile: ./docker/Dockerfile
    container_name: server
    env_file:
      - .env
    volumes:
      - shared-data:/shared
    ports:
      - "5252:${PORT}"
    networks:
      - server-net
    depends_on:
      - mongo
    deploy:
      resources:
        limits:
          cpus: '1.5'
          memory: 3584M 
        reservations:
          cpus: '0.25'
          memory: 256M 


networks:
  server-net:

volumes:
  shared-data: